theme: jekyll-theme-midnight
title: Welcome to Ireaneus Linux Cheat Sheets webpage
Description: Linux Commandline cheatsheets with valuable examples 
url: https://ireaneus.github.io/linux-cheat-sheets/
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
